### ISSUE TITLE
Question about the "upsampling method" for the extracted feature.

### ISSUE THREAD

**Issue by rtst777** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#17]
Hi, the function [forward_fine_tune](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/e6a79ed0c63d6d24e6db21bd44c045fed7c727c6/transformer/solver.py#L742) uses [tile_representations](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/e6a79ed0c63d6d24e6db21bd44c045fed7c727c6/transformer/solver.py#L562) to upsample the extracted features, which simply duplicates each feature frame `downsample_rate` times along the time axis.

I am wondering why you choose this specific upsampling method instead of other methods, such as splitting one feature frame to `downsample_rate` consecutive frames? Does this specific upsampling method provide the best performance?

Thanks in advance!

**Comment by andi611** [comment]
We did not explore other upsampling methods, so it is not guaranteed to generate the best performance.
In our recent study, we always use a downsample rate of 1, which means no downsampling (thus upsampling is not required).
This is because we find `downsample_rate=1` provides better results, at the cost of requiring more GPU memory.

**Comment by rtst777** [comment]
I see. Thanks for the information!
