### ISSUE TITLE
How to resume downstream training

### ISSUE THREAD

**Issue by liu-x-p** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#40]
Thank you for sharing your great work!
I have a trouble when I learn to use this toolkit. I was trying to use the pre-trained mockingjay model on librispeech dataset, and then performed fine-tune for the phone classification task. Then I noticed the `total step` was 500000, which was same as the step for  pre-training the model, then I stopped the training and reduced the value of `total step`. But when I wanted to resume at the saved fine-tune model, it reported error:
```
[run_downstream] - getting upstream model: transformer
Traceback (most recent call last):
  File "run_downstream.py", line 222, in <module>
    main()
  File "run_downstream.py", line 202, in main
    upstream_model = get_upstream_model(args) ######### plug in your upstream pre-trained model here #########
  File "run_downstream.py", line 111, in get_upstream_model
    upstream_model = TRANSFORMER(options, args.input_dim, online_config=args.online_config)
  File "/home/speech/Self-Supervised-Speech-Pretraining-and-Representation-Learning/transformer/nn_transformer.py", line 305, in __init__
    super(TRANSFORMER, self).__init__(options, inp_dim, config, online_config)
  File "/home/speech/Self-Supervised-Speech-Pretraining-and-Representation-Learning/transformer/nn_transformer.py", line 61, in __init__
    self.model_config = TransformerConfig(self.config)
  File "/home/speech/Self-Supervised-Speech-Pretraining-and-Representation-Learning/transformer/model.py", line 27, in __init__
    self.downsample_rate = config['transformer']['downsample_rate']
KeyError: 'transformer'
```

The command I use was `python run_downstream.py --run=phone_linear --upstream=transformer --ckpt=./result/result_transformer_cpc_phone/exp_632/states-70000.ckpt`
and `states-70000.ckpt` is a saved ckpt during fine-tune

**Comment by andi611** [comment]
Hi, the `--ckpt` is for loading the pre-trained model and not downstream ckpt.
However, I've added the function you need in this update: https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/91be1dc43b039a55e5f5547fb6114582a26eb14f

Now you can use the following command to resume downstream training:
`python run_downstream.py --resume=./result/result_transformer_cpc_phone/exp_632/states-70000.ckpt`

**Comment by liu-x-p** [comment]
@andi611 Thank you for reply! I will update the code and try that.

**Comment by joram5** [comment]
Hi Andy,

I refreshed my code to get the --resume option. I am getting the following fail.

I am running:

python run_downstream.py --resume=./result/result_transformer_cpc_phone/exp_632/states-8000.ckpt

I get the following fail:

[run_downstream] - getting upstream model: transformer
[Transformer] - Pre-trained weights loaded!
[Transformer] - Number of parameters: 85087488
Traceback (most recent call last):
  File "run_downstream.py", line 248, in <module>
    main()
  File "run_downstream.py", line 231, in main
    train_loader, dev_loader, test_loader = get_all_dataloaders(args, config['dataloader'])
KeyError: 'dataloader'

What can be the problem?

Regards
Joram

**Comment by andi611** [comment]
> Hi Andy,
> 
> I refreshed my code to get the --resume option. I am getting the following fail.
> 
> I am running:
> 
> python run_downstream.py --resume=./result/result_transformer_cpc_phone/exp_632/states-8000.ckpt
> 
> I get the following fail:
> 
> [run_downstream] - getting upstream model: transformer
> [Transformer] - Pre-trained weights loaded!
> [Transformer] - Number of parameters: 85087488
> Traceback (most recent call last):
> File "run_downstream.py", line 248, in
> main()
> File "run_downstream.py", line 231, in main
> train_loader, dev_loader, test_loader = get_all_dataloaders(args, config['dataloader'])
> KeyError: 'dataloader'
> 
> What can be the problem?

Hi,

I found that this error is caused by a bug in our code.
For your current situation,
please change [this line](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/9d83f757aa9454d72979e626ebf8124913b3cf5f/run_downstream.py#L101) to the following:
```python
config = yaml.load(open('/result/result_transformer_cpc_phone/exp_632/downstream.yaml', 'r'), Loader=yaml.FullLoader)
```

I've updated a permanent fix to this bug in this [commit](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/d2aafd81af19f1e3924abec18055ed8b17cc6093), you can refresh your code once again after you get your current ckpt resumed with the previous temporary fix.

I hope this helps,
Andy

**Comment by joram5** [comment]
Hi Andy,


The resume is running very well now. I have further two questions if it is ok with you:


  1.  After each resume there is a drop in acuracy (ACC), is this expected behaviour? :

[cid:f8c2ef0c-22f0-4c67-914a-e296f313f580]


        2. I have run 340000 iterations so far. Does the above convergance rate seem reasonable? Should I try to increase the learning rate?

Further info:

I started with the following command line:

python run_downstream.py --run=phone_linear --upstream=transformer --ckpt=../S3PRL/mockingjay/fmllrLarge960-T-libri/states-1000000.ckpt

Resume commands lines are in the form:

python run_downstream.py --resume=./result/result_transformer_cpc_phone/exp_632/states-324000.ckpt


Thank you

Regards
Joram

________________________________
מאת: Joram Peer <Joram.Peer@s.afeka.ac.il>
‏‏נשלח: יום רביעי 28 אוקטובר 2020 00:59
‏‏אל: andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning <reply@reply.github.com>
עותק: Comment <comment@noreply.github.com>
‏‏נושא: Re:‏ [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning] How to resume downstream training (#40)


Thanks Andy

Resume  is working fine now

Regards
Joram

________________________________
מאת: Andy T. Liu <notifications@github.com>
‏‏נשלח: יום שלישי 27 אוקטובר 2020 09:20
‏‏אל: andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning <Self-Supervised-Speech-Pretraining-and-Representation-Learning@noreply.github.com>
עותק: Joram Peer <Joram.Peer@s.afeka.ac.il>; Comment <comment@noreply.github.com>
‏‏נושא: Re: [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning] How to resume downstream training (#40)


Hi Andy,

I refreshed my code to get the --resume option. I am getting the following fail.

I am running:

python run_downstream.py --resume=./result/result_transformer_cpc_phone/exp_632/states-8000.ckpt

I get the following fail:

[run_downstream] - getting upstream model: transformer
[Transformer] - Pre-trained weights loaded!
[Transformer] - Number of parameters: 85087488
Traceback (most recent call last):
File "run_downstream.py", line 248, in
main()
File "run_downstream.py", line 231, in main
train_loader, dev_loader, test_loader = get_all_dataloaders(args, config['dataloader'])
KeyError: 'dataloader'

What can be the problem?

Hi,

I found that this error is caused by a bug in our code.
For your current situation,
please change this line<https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/9d83f757aa9454d72979e626ebf8124913b3cf5f/run_downstream.py#L101> to the following:

config = yaml.load(open('/result/result_transformer_cpc_phone/exp_632/downstream.yaml', 'r'), Loader=yaml.FullLoader)

I've updated a permanent fix to this bug in this commit<https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/d2aafd81af19f1e3924abec18055ed8b17cc6093>, you can refresh your code once again after you get your current ckpt resumed with the previous temporary fix.

I hope this helps,
Andy

**Comment by andi611** [comment]
Hi,

Since I never used the `--resume` function, so my experience on this subject is limited.
However, my co-worker tells me that the "drop" (a vertical line?) you see may be caused by a mismatch in the time step for the Tensorboard log. Hence this is an error in the display of the training log, and it does not really affect the model's performance.
We've updated this [line](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/6690f646a60c860d5e964342139faad294c2c526), I think it will resolve this mismatched timestep issue.

For your second question, although I am having trouble seeing the image you've provided, but I believe the convergence rate is reasonable. I've run this task many times (without the use of --resume), the results are pretty stable.

Phone classification over 100 hrs of training data should take a while for the model to converge (on training set). However, the performance on the test set is already very high even after the first 10000 steps of training.

**Comment by joram5** [comment]
Thanks Andy

Regards
Joram

________________________________
